name: Publish Github Release

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      repo:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  publish-github-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create the semantic-release note
        run: git notes --ref semantic-release add -f -m '{"channels":["${{ inputs.branch }}"]}' ${{ inputs.version }}

      - name: Push semantic-release note
        run: git push --force origin refs/notes/semantic-release

      - name: Undraft the release
        uses: LogicOverSnacks/actions-publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          repo: ${{ inputs.repo }}
