name: Publish

on:
  push:
    branches:
      - main
      - demo
      - beta
      - alpha
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-release:
    name: Prepare Release
    uses: ./.github/workflows/prepare-release.yml
    with:
      ref: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-electron-app:
    name: Build Electron App
    uses: ./.github/workflows/build-electron-app.yml
    needs:
      - prepare-release
    strategy:
      matrix:
        os:
          - macos-14
          - ubuntu-latest
          - windows-latest
    with:
      branch: ${{ github.ref_name }}
      operatingSystem: ${{ matrix.os }}
      version: ${{ needs.prepare-release.outputs.version }}
    secrets:
      appleAPIIssuerID: ${{ secrets.APPLE_API_ISSUER_ID }}
      appleAPIKeyContent: ${{ secrets.APPLE_API_KEY_CONTENT }}
      appleAPIKeyID: ${{ secrets.APPLE_API_KEY_ID }}
      appleCertData: ${{ secrets.APPLE_CERT_DATA }}
      appleCertKeychainPassword: ${{ secrets.APPLE_CERT_KEYCHAIN_PASSWORD }}
      appleCertPassword: ${{ secrets.APPLE_CERT_PASSWORD }}
      token: ${{ secrets.GITHUB_TOKEN }}

  publish-github-release:
    name: Publish Github Release
    uses: ./.github/workflows/publish-github-release.yml
    needs:
      - build-electron-app
      - prepare-release
    with:
      repo: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish-to-steam:
    name: Publish to Steam
    uses: ./.github/workflows/publish-to-steam.yml
    needs:
      - prepare-release
      - publish-github-release
    with:
      branch: ${{ github.ref_name }}
      version: ${{ needs.prepare-release.outputs.version }}
      zipPrefix: The-Inn-at-Nightfall
    secrets:
      steamAppID: ${{ secrets.STEAM_APP_ID }}
      steamBuildUsername: ${{ secrets.STEAM_BUILD_USERNAME }}
      steamBuildConfigVDF: ${{ secrets.STEAM_BUILD_CONFIG_VDF }}
      steamDemoAppID: ${{ secrets.STEAM_DEMO_APP_ID }}
      token: ${{ secrets.GITHUB_TOKEN }}

  # publish-to-itch:
  #   name: Publish to Itch
  #   uses: ./.github/workflows/publish-to-itch.yml
  #   needs:
  #     - prepare-release
  #     - publish-github-release
  #   strategy:
  #     matrix:
  #       platform:
  #         - alias: linux
  #           arch: x64
  #           name: linux
  #         - alias: osx
  #           arch: universal
  #           name: darwin
  #         - alias: windows
  #           arch: x64
  #           name: win32
  #   with:
  #     platformAlias: ${{ matrix.platform.alias }}
  #     platformArch: ${{ matrix.platform.arch }}
  #     platformName: ${{ matrix.platform.name }}
  #     version: ${{ needs.prepare-release.outputs.version }}
  #     zipPrefix: The-Inn-at-Nightfall
  #   secrets: inherit
